### ISSUE TITLE
Update GitHub Actions template

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#345]
actions template can be updated to login-action v3 and build-push-action v5

Example actions file (tested, works)

```
name: kthcloud-ci-app
"on":
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_TAG }}
```
